### ISSUE TITLE
Create mani folder?

### ISSUE THREAD

**Issue by keeganstoner** [MelissaChen15/control-vc#2]
I have a set of my own voice samples that I want to try, but some of the inference.sh scripts require /mani/wavelist.txt and other stuff in the mani directory. Is there a script that generates the mani files from voice samples, or would I have to train from scratch to make these files? Or do I have to create them another way?

Thanks!

**Comment by hcl14** [comment]
It's because the folders are not created, so the script does not write wavelist. Add to the beginning of `inference.sh`:

```
CUDA_VISIBLE_DEVICES=0
BASE_DIR=./example
CKPT_DIR=./checkpoints
MANI_DIR=${BASE_DIR}/mani
OUT_DIR=${BASE_DIR}/synthesis
WAV_DIR_IN=${BASE_DIR}/inputs
WAV_DIR_PROCESSED=${MANI_DIR}/wavs_padded
EXT=.wav #.flac
OUT_QUANTIZED_FILE=${MANI_DIR}/hubert_codes.txt
MEL_DIR=$MANI_DIR/mels

mkdir "$MANI_DIR"
mkdir "$OUT_DIR"
mkdir "$WAV_DIR_PROCESSED"
mkdir "$MEL_DIR"
```

Also you need to add to `infer_hubert.py`:

```
    parser.add_argument(
        "--features_pget_wavlist4hubertath", type=str, default=None,
    )
```

And rename `checkpoints/embed_f0stat2/g_00350000.zip` and `checkpoints/vctk_f0_vq/g_00400000.zip`  to `checkpoints/embed_f0stat2/g_00350000` and `checkpoints/vctk_f0_vq/g_00400000`.

The speaker folders and files inside should be named as `XXX/XXX_whatever.wav`, other wise if will fail in the middle with wrong dictionary keys.

Also you need `scikit-learn==0.24.0`, with 1.x it fails

**Comment by kay9012** [comment]
> It's because the folders are not created, so the script does not write wavelist. Add to the beginning of `inference.sh`:
> 
> ```
> CUDA_VISIBLE_DEVICES=0
> BASE_DIR=./example
> CKPT_DIR=./checkpoints
> MANI_DIR=${BASE_DIR}/mani
> OUT_DIR=${BASE_DIR}/synthesis
> WAV_DIR_IN=${BASE_DIR}/inputs
> WAV_DIR_PROCESSED=${MANI_DIR}/wavs_padded
> EXT=.wav #.flac
> OUT_QUANTIZED_FILE=${MANI_DIR}/hubert_codes.txt
> MEL_DIR=$MANI_DIR/mels
> 
> mkdir "$MANI_DIR"
> mkdir "$OUT_DIR"
> mkdir "$WAV_DIR_PROCESSED"
> mkdir "$MEL_DIR"
> ```
> 
> Also you need to add to `infer_hubert.py`:
> 
> ```
>     parser.add_argument(
>         "--features_pget_wavlist4hubertath", type=str, default=None,
>     )
> ```
> 
> And rename `checkpoints/embed_f0stat2/g_00350000.zip` and `checkpoints/vctk_f0_vq/g_00400000.zip` to `checkpoints/embed_f0stat2/g_00350000` and `checkpoints/vctk_f0_vq/g_00400000`.
> 
> The speaker folders and files inside should be named as `XXX/XXX_whatever.wav`, other wise if will fail in the middle with wrong dictionary keys.
> 
> Also you need `scikit-learn==0.24.0`, with 1.x it fails

May I ask a question about the "g_00400000" ?Is it a file or something else after rename it?
