### ISSUE TITLE
About sound quality

### ISSUE THREAD

**Issue by SylphWind** [MelissaChen15/control-vc#3]
Hi Melissa,

I have tried your training code by my own data set with 330K steps.
However, I would got a voice clip with some dirty sounds after voice conversion, and I notices periodic horizontal line patterns in the spectrum line the below picture.
![image](https://user-images.githubusercontent.com/12636956/202602642-b3692537-78c2-4905-8ac3-8c330cbdd677.png)
If using your pretrained model, this issue would not happen.
Did you encounter this issues and how you solved it?

Thanks!

**Comment by MelissaChen15** [comment]
Hi Nekomaru,

Thanks for using my code! I'm sorry to hear you're experiencing periodic artifacts. I haven't seen that issue in my own training process. I suspect it may be related to preprocessing. Can you let me know what dataset and sample rate you're using? Also, can you confirm it is not caused by overfitting by looking at the output from earlier epochs?

Also, I apologize for the delay in my response. Has the issue been resolved since you first reported it? Please let me know.

Melissa

**Comment by SylphWind** [comment]
Dear Melissa,

Thanks for your kindly reply.
I am not studying this issue so I cannot ensure whether it is caused by preprocessing so far.
I would close this issue and maybe re-studying if necessary.
Thanks!
